services:
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:v1.0.0
    volumes:
      - ./mealie-data:/app/data
    environment:
      - ALLOW_SIGNUP=true
    network_mode: "host"
    depends_on:
      - tailscale
    restart: unless-stopped

  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:latest
    hostname: ${TAILSCALE_HOSTNAME}
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ./tailscale-state:/var/lib/tailscale
      - ./tailscale-config:/config
    network_mode: "host"
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
